/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "text-noise": {
    name: "text-noise",
    description: "A text animation with noise overlay",
    type: "registry:component",
    registryDependencies: [],
    files: [{
      path: "registry/ui/TextNoise.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "public/noise.gif",
      type: "registry:file",
      target: "~/public/noise.gif"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/TextNoise.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-circle": {
    name: "text-circle",
    description: "A text animation with animated circle outline",
    type: "registry:component",
    registryDependencies: ["motion"],
    files: [{
      path: "registry/ui/TextCircle.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/TextCircle.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-underline": {
    name: "text-underline",
    description: "A text animation with animated underline",
    type: "registry:component",
    registryDependencies: ["motion"],
    files: [{
      path: "registry/ui/TextUnderline.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/TextUnderline.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-highlight": {
    name: "text-highlight",
    description: "A text animation with marker-like highlighting",
    type: "registry:component",
    registryDependencies: ["motion"],
    files: [{
      path: "registry/ui/TextHighlight.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/TextHighlight.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-scan": {
    name: "text-scan",
    description: "Text scan animation on hover",
    type: "registry:component",
    registryDependencies: ["motion"],
    files: [{
      path: "registry/ui/TextScan.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "public/noise.gif",
      type: "registry:file",
      target: "~/public/noise.gif"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/TextScan.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "sliding-badge": {
    name: "sliding-badge",
    description: "Animated Badge with messages sliding from left to right",
    type: "registry:component",
    registryDependencies: ["motion"],
    files: [{
      path: "registry/ui/SlidingBadge.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/SlidingBadge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "pixel-card": {
    name: "pixel-card",
    description: "Card that reveals pixelized background on hover",
    type: "registry:component",
    registryDependencies: ["motion"],
    files: [{
      path: "registry/ui/PixelCard.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "public/scripts/pixel.js",
      type: "registry:file",
      target: "~/public/scripts/pixel.js"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/PixelCard.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "rays": {
    name: "rays",
    description: "Light rays effect, perfect for drawing attention",
    type: "registry:component",
    registryDependencies: ["motion"],
    files: [{
      path: "registry/ui/Rays.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/Rays.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hero-media": {
    name: "hero-media",
    description: "Customizable component for Hero Section capabale of displaying images or videos in a modal.",
    type: "registry:component",
    registryDependencies: ["motion","dialog"],
    files: [{
      path: "registry/ui/HeroMedia.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/HeroMedia.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-cubic": {
    name: "text-cubic",
    description: "Text animation with animated letters looking like rubik's cube.",
    type: "registry:component",
    registryDependencies: ["motion"],
    files: [{
      path: "registry/ui/TextCubic.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/TextCubic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "bento-grid": {
    name: "bento-grid",
    description: "Bento grid with eye catching grainy gradient",
    type: "registry:component",
    registryDependencies: [],
    files: [{
      path: "registry/ui/BentoGrid.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/BentoGrid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }